platform :ios, '7.0'
inhibit_all_warnings!
##########LocalPod##########

#zip解压
#pod 'ZipArchive'
#网络请求
pod 'AFNetworking'
#瀑布流布局
#pod 'CHTCollectionViewWaterfallLayout'
#提示
#pod 'MBProgressHUD'
#下拉刷新
pod 'MJRefresh'
#友盟统计
#pod 'UMengAnalytics'
#友盟反馈
#pod 'UMengFeedback'
#图片加载
pod 'SDWebImage'
